/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.gui;

import cliente.dominio.PessoaJuridica;
import cliente.service.Servico;
import cliente.service.ServicoClienteCNPJ;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CadastroPJuridica extends javax.swing.JFrame {
    private Servico service = new Servico();

    /**
     * Creates new form CadastroPJuridica
     */
    public CadastroPJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeCadPJuridica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inscCadPJuridica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enderecoCadPJuridica = new javax.swing.JTextField();
        btnCadPJuridica = new javax.swing.JToggleButton();
        cnpjCadPJuridica = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE PESSOA JURÍDICA");

        jLabel2.setText("Nome:");

        nomeCadPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCadPJuridicaActionPerformed(evt);
            }
        });

        jLabel3.setText("CNPJ:");

        jLabel4.setText("Inscrição Estadual:");

        jLabel5.setText("Endereço:");

        enderecoCadPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoCadPJuridicaActionPerformed(evt);
            }
        });

        btnCadPJuridica.setBackground(new java.awt.Color(153, 153, 255));
        btnCadPJuridica.setText("CADASTRAR");
        btnCadPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPJuridicaActionPerformed(evt);
            }
        });

        try {
            cnpjCadPJuridica.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(nomeCadPJuridica)
                                    .addComponent(jLabel3)
                                    .addComponent(inscCadPJuridica)
                                    .addComponent(enderecoCadPJuridica)
                                    .addComponent(cnpjCadPJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cnpjCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inscCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCadPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadPJuridicaActionPerformed
    }//GEN-LAST:event_nomeCadPJuridicaActionPerformed

    private void enderecoCadPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoCadPJuridicaActionPerformed
    }//GEN-LAST:event_enderecoCadPJuridicaActionPerformed

    private void btnCadPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPJuridicaActionPerformed
        if (validarCampos()){
            cliente.dominio.Cliente cliente = new cliente.dominio.Cliente();
            cliente.setNome(nomeCadPJuridica.getText());
            cliente.setEndereco(enderecoCadPJuridica.getText());
            
            PessoaJuridica pessoa = new PessoaJuridica();
            pessoa.setCnpj(formatarCnpj());
            pessoa.setInscEstadual(inscCadPJuridica.getText());
            
            if (service.buscarCNPJ(formatarCnpj())){
                JOptionPane.showMessageDialog(null, "CNPJ já cadastrado");

            }
            else{
                try {
                    if (service.cadClientePJuridica(cliente, pessoa)){
                        limparCampos();
                        JOptionPane.showMessageDialog(null, "Cliente Cadastrado!");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Erro ao realizar cadastro.");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro inesperado" + ex);
                }
            }
        }
    }//GEN-LAST:event_btnCadPJuridicaActionPerformed

       private boolean validarCampos(){
        String strCnpj = cnpjCadPJuridica.getText();
        ServicoClienteCNPJ cnpj = new ServicoClienteCNPJ(strCnpj);
        
        if (service.isEmpty(String.valueOf(nomeCadPJuridica.getText()))){
            JOptionPane.showMessageDialog(null, "Nome inválido");
            return false;
        }
        else if (!cnpj.isCNPJ()){
            JOptionPane.showMessageDialog(null, "CNPJ inválido");
            return false;
        }
        else if (service.isEmpty(inscCadPJuridica.getText())){
            JOptionPane.showMessageDialog(null, "Inscrição Estadual vazia");
            return false;
        }
        else if (service.isEmpty(String.valueOf(enderecoCadPJuridica.getText()))){
            JOptionPane.showMessageDialog(null, "Endereço inválido");
            return false;
        }
        else{
            return true;
        }
    }
       
    private String formatarCnpj(){
        String cnpj = cnpjCadPJuridica.getText();
        cnpj = cnpj.replace(".", "");
        cnpj = cnpj.replace("/","");
        cnpj = cnpj.replace("-", "");
        return cnpj;
    }
    
    
    private void limparCampos(){
        nomeCadPJuridica.setText("");
        cnpjCadPJuridica.setText(null);
        enderecoCadPJuridica.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPJuridica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadPJuridica;
    private javax.swing.JFormattedTextField cnpjCadPJuridica;
    private javax.swing.JTextField enderecoCadPJuridica;
    private javax.swing.JTextField inscCadPJuridica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nomeCadPJuridica;
    // End of variables declaration//GEN-END:variables
}
