/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veiculo.gui;

import cliente.service.Servico;
import filial.dominio.Filial;
import filial.service.ServicoFilial;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import veiculo.dominio.Veiculo;
import veiculo.service.VeiculoService;

/**
 *
 * @author bruno.an
 */
public class CadastroVeiculo extends javax.swing.JFrame {
    private Servico service = new Servico();
    private ServicoFilial serviceFilial = new ServicoFilial();
    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCadVeiculo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        veiculoPlaca = new javax.swing.JTextField();
        veiculoMotor = new javax.swing.JTextField();
        veiculoKm = new javax.swing.JTextField();
        veiculoFilial = new javax.swing.JTextField();
        veiculoChassi = new javax.swing.JTextField();
        veiculoCor = new javax.swing.JTextField();
        tipoVeiculo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel8)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel6.setText("CADASTRO VEÍCULO");

        jLabel1.setText("Placa:");

        jLabel2.setText("Número Chassi");

        jLabel3.setText("Número Motor");

        jLabel4.setText("Quilometragem");

        jLabel5.setText("Nome Filial:");

        btnCadVeiculo.setBackground(new java.awt.Color(153, 153, 255));
        btnCadVeiculo.setText("CADASTRAR");
        btnCadVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeiculoActionPerformed(evt);
            }
        });

        jLabel7.setText("Cor");

        veiculoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPlacaActionPerformed(evt);
            }
        });

        veiculoMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoMotorActionPerformed(evt);
            }
        });

        veiculoKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoKmActionPerformed(evt);
            }
        });

        veiculoFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoFilialActionPerformed(evt);
            }
        });

        veiculoChassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoChassiActionPerformed(evt);
            }
        });

        veiculoCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCorActionPerformed(evt);
            }
        });

        tipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        tipoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVeiculoActionPerformed(evt);
            }
        });

        jLabel9.setText("Tipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnCadVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(veiculoPlaca)
                                    .addComponent(veiculoMotor)
                                    .addComponent(veiculoKm)
                                    .addComponent(veiculoFilial)
                                    .addComponent(veiculoChassi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(veiculoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(tipoVeiculo, 0, 100, Short.MAX_VALUE))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(veiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(veiculoChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(veiculoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(veiculoKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(veiculoFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeiculoActionPerformed
        if(validarCampos()){
            if (serviceFilial.verificarFilial(veiculoFilial.getText())){
                Filial filial = serviceFilial.buscarFilial(veiculoFilial.getText());
                Veiculo veiculo = new Veiculo();
                VeiculoService vService = new VeiculoService();
                veiculo.setPlaca(veiculoPlaca.getText());
                veiculo.setNumeroChassi(veiculoChassi.getText());
                veiculo.setNumeroMotor(veiculoMotor.getText());
                int Km = parseInt(veiculoKm.getText());
    //            int filial = parseInt(veiculoFilial.getText());
                veiculo.setQuilometragem(Km);
                veiculo.setFilial(filial.getId());
                veiculo.setTipoVeiculo(tipoVeiculo.getItemCount());
                veiculo.setCor(veiculoCor.getText());
                if(!vService.isVeiculo(veiculoPlaca.getText())){
                    vService.cadastrarVeiculo(veiculo);
                    JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
                    veiculoPlaca.setText("");
                    veiculoChassi.setText("");
                    veiculoMotor.setText("");
                    veiculoKm.setText("");
                    veiculoFilial.setText("");
                    veiculoCor.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Veículo já cadastrado");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Esta Filial não existe");
            }
//            try{
//              if(vService.buscarVeiculo(veiculoPlaca.getText()).equals(veiculo)){
//               JOptionPane.showMessageDialog(null, "Veículo já cadastrado");
//            }  
//            }catch(NullPointerException ex){
//                vService.cadastrarVeiculo(veiculo);
//            }
                
            
            
            
        }
    }//GEN-LAST:event_btnCadVeiculoActionPerformed

    private void veiculoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPlacaActionPerformed

    private void veiculoMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoMotorActionPerformed

    private void veiculoKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoKmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoKmActionPerformed

    private void veiculoFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoFilialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoFilialActionPerformed

    private void veiculoChassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoChassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoChassiActionPerformed

    private void veiculoCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCorActionPerformed

    private void tipoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVeiculo().setVisible(true);
            }
        });
    }
    
    private boolean validarCampos(){
        if (service.isEmpty(String.valueOf(veiculoPlaca.getText()))){
            JOptionPane.showMessageDialog(null, "Placa inválida");
            return false;
        }
        else if(service.isEmpty(String.valueOf(veiculoChassi.getText()))){
            JOptionPane.showMessageDialog(null, "Chassi inválido");
            return false;
        }
        else if(service.isEmpty(String.valueOf(veiculoMotor.getText()))){
            JOptionPane.showMessageDialog(null, "Motor inválido");
            return false;
        }
        else if(service.isEmpty(String.valueOf(veiculoKm.getText()))){
            JOptionPane.showMessageDialog(null, "Quilometragem inválida");
            return false;
        }
        else if(!service.isEmpty(String.valueOf(veiculoKm.getText()))){
            try{
                int x = parseInt(veiculoKm.getText());
            }catch(NumberFormatException ex){
                 JOptionPane.showMessageDialog(null, "Formato de Quilometragem inválida");
                 return false;
            }  
        }
        else if(service.isEmpty(String.valueOf(veiculoFilial.getText()))){
            JOptionPane.showMessageDialog(null, "Filial inválida");
            return false;
        }
        else if(!service.isEmpty(String.valueOf(veiculoFilial.getText()))){
            try{
                int x = parseInt(veiculoFilial.getText());
            }catch(NumberFormatException ex){
                 JOptionPane.showMessageDialog(null, "Formato de Quilometragem inválida");
                 return false;
            }  
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tipoVeiculo;
    private javax.swing.JTextField veiculoChassi;
    private javax.swing.JTextField veiculoCor;
    private javax.swing.JTextField veiculoFilial;
    private javax.swing.JTextField veiculoKm;
    private javax.swing.JTextField veiculoMotor;
    private javax.swing.JTextField veiculoPlaca;
    // End of variables declaration//GEN-END:variables
}
