/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package locacao.gui;

import cliente.dominio.Cliente;
import cliente.service.Servico;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import locacao.dominio.Locacao;
import locacao.service.LocacaoService;
import reserva.service.ReservaService;
import veiculo.dominio.Veiculo;
import veiculo.service.VeiculoService;

/**
 *
 * @author Kimbelly
 */
public class CadastrarLocacao extends javax.swing.JFrame {

    private int tipoCliente = 0;//1-PESSOA FISICA 2-PESSOA JURIDICA
    private Servico service = new Servico();
    private LocacaoService locaService = new LocacaoService();


    /** Creates new form Alocacao */
    public CadastrarLocacao() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    private String formatarData(String nasc){
        String ano = nasc.substring(6, 10);

        String dia = nasc.substring(0, 2);

        String mes = nasc.substring(3, 5);

        return ano+"-"+mes+"-"+dia;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarCPF = new javax.swing.JFormattedTextField();
        buscaEndePFisica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAlocarVeiculo = new javax.swing.JButton();
        tipoLocacao = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tipoClienteBoxLoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataRetiradaLocacao = new javax.swing.JFormattedTextField();
        dataDevoluLocacao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cnhMotorista = new javax.swing.JTextField();
        placaVeiculoLoc = new javax.swing.JTextField();
        campoDado = new javax.swing.JTextField();

        try {
            buscarCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        buscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCPFActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Tipo:");

        btnAlocarVeiculo.setText("ALOCAR VEÍCULO");
        btnAlocarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocarVeiculoActionPerformed(evt);
            }
        });

        tipoLocacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        tipoLocacao.setActionCommand("comboBoxChangedTipoCliente");
        tipoLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLocacaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo Cliente:");

        tipoClienteBoxLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pessoa Física","Pessoa Juridica"}));
        tipoClienteBoxLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteBoxLocActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF ou CNPJ:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("LOCAÇÃO DO VEÍCULO");

        jLabel2.setText("Data de retirada:");

        try {
            dataRetiradaLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataRetiradaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRetiradaLocacaoActionPerformed(evt);
            }
        });

        try {
            dataDevoluLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDevoluLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDevoluLocacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de devolução:");

        jLabel4.setText("CNH do motorista:");

        jLabel11.setText("Placa do veículo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoClienteBoxLoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(campoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tipoLocacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(0, 146, Short.MAX_VALUE)))))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataRetiradaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(cnhMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataDevoluLocacao)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addComponent(placaVeiculoLoc))
                                .addGap(44, 44, 44))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnAlocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataRetiradaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDevoluLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnhMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placaVeiculoLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoClienteBoxLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAlocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlocarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocarVeiculoActionPerformed
        if (validarCampos()){
            Locacao locacao = new Locacao();
            locacao.setDataRetirada(formatarData(dataRetiradaLocacao.getText()));
            locacao.setDataDevolucao(formatarData(dataDevoluLocacao.getText()));
            locacao.setCnhMotorista(parseInt(cnhMotorista.getText()));
            locacao.setPlacaVeiculo(placaVeiculoLoc.getText());
            Cliente cliente = new Cliente();
            if (tipoCliente == 0){
                cliente=service.buscarPessoaFisica(campoDado.getText());
            }
            else{
                cliente=service.buscarPessoaJuridica(campoDado.getText());
            }
            
            locacao.setIdCliente(cliente.getId());
            if (locaService.doLocacao(locacao)){
                JOptionPane.showMessageDialog(null, "Locacao realizada com sucesso");
            }
        }        
    }//GEN-LAST:event_btnAlocarVeiculoActionPerformed

    private boolean verificarPessoa(){
        if(tipoClienteBoxLoc.getSelectedIndex()== 0){
            tipoCliente = 0;
            return service.buscarCPF(campoDado.getText());
            
        }else{
            tipoCliente = 1; 
            return service.buscarCNPJ(campoDado.getText());               
        }
        
    }
    
    private void tipoLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLocacaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tipoLocacaoActionPerformed

    private void tipoClienteBoxLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteBoxLocActionPerformed

    }//GEN-LAST:event_tipoClienteBoxLocActionPerformed

    private void dataRetiradaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRetiradaLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRetiradaLocacaoActionPerformed

    private void dataDevoluLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDevoluLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDevoluLocacaoActionPerformed

    private void buscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCPFActionPerformed

    }//GEN-LAST:event_buscarCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocarVeiculo;
    private javax.swing.JTextField buscaEndePFisica;
    private javax.swing.JFormattedTextField buscarCPF;
    private javax.swing.JTextField campoDado;
    private javax.swing.JTextField cnhMotorista;
    private javax.swing.JFormattedTextField dataDevoluLocacao;
    private javax.swing.JFormattedTextField dataRetiradaLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField placaVeiculoLoc;
    private javax.swing.JComboBox<String> tipoClienteBoxLoc;
    private javax.swing.JComboBox<String> tipoLocacao;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        String dataRetirada = formatarData(dataRetiradaLocacao.getText());
        String dataDevolucao = formatarData(dataDevoluLocacao.getText());
        
        LocacaoService lService = new LocacaoService();
        Servico servico = new Servico();        
        if(!lService.isIntervaloDatasCerto(dataRetirada, dataDevolucao)){
            JOptionPane.showMessageDialog(null, "Datas inválidas");
            return false;
        }        
        else if (!service.verificarMotorista(parseInt(cnhMotorista.getText()))){
            JOptionPane.showMessageDialog(null, "Motorista não cadastrado");
            return false;
        }
        else if (!locaService.buscarPlaca(placaVeiculoLoc.getText())){
            JOptionPane.showMessageDialog(null, "Placa não encontrada");
            return false;
        }
        else if (!verificarPessoa()){
            if (tipoCliente == 0){
               JOptionPane.showMessageDialog(null, "CPF não encontrado");
               return false;
            }
            else{
                JOptionPane.showMessageDialog(null, "CNPJ não encontrado");
                return false;
            }
        }

        return true;
    }
    private void limparCampos() {
        dataDevoluLocacao.setText("");
        dataRetiradaLocacao.setText("");
        campoDado.setText("");
        campoDado.setText("");
        placaVeiculoLoc.setText("");
        
    }

}
