/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package locacao.gui;

import cliente.dominio.Cliente;
import cliente.service.Servico;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import locacao.dominio.Locacao;
import locacao.service.LocacaoService;
import reserva.service.ReservaService;
import veiculo.dominio.Veiculo;
import veiculo.service.VeiculoService;

/**
 *
 * @author Kimbelly
 */
public class LocacaoJF extends javax.swing.JFrame {

    private int tipocliente = 1;//1-PESSOA FISICA 2-PESSOA JURIDICA
    Servico service = new Servico();


    /** Creates new form Alocacao */
    public LocacaoJF() {
        initComponents();
    }
    private String formatarData(String nasc){
        String ano = nasc.substring(6, 10);

        String dia = nasc.substring(0, 2);

        String mes = nasc.substring(3, 5);

        return ano+"-"+mes+"-"+dia;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        btnAlocarVeiculo = new javax.swing.JButton();
        tipoLocacao = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tipoClienteBox = new javax.swing.JComboBox<>();
        campoDado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataRetiradaLocacao = new javax.swing.JFormattedTextField();
        dataDevoluLocacao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cnhMotorista = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        placaVeiculoLoc = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        btnRemoverLocacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Tipo:");

        btnAlocarVeiculo.setText("ALOCAR VEÍCULO");
        btnAlocarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocarVeiculoActionPerformed(evt);
            }
        });

        tipoLocacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2"}));
        tipoLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLocacaoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo Cliente:");

        tipoClienteBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Pessoa Física","Pessoa Juridica"}));
        tipoClienteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoClienteBoxActionPerformed(evt);
            }
        });

        campoDado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDadoActionPerformed(evt);
            }
        });

        jLabel6.setText("CPF ou CNPJ:");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText("LOCAÇÃO DO VEÍCULO");

        jLabel2.setText("Data de retirada:");

        try {
            dataRetiradaLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataRetiradaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRetiradaLocacaoActionPerformed(evt);
            }
        });

        try {
            dataDevoluLocacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataDevoluLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDevoluLocacaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de devolução:");

        jLabel4.setText("CNH do motorista:");

        jScrollPane1.setViewportView(cnhMotorista);

        jScrollPane2.setViewportView(placaVeiculoLoc);

        jLabel11.setText("Placa do veículo:");

        btnRemoverLocacao.setText("REMOVER LOCAÇÃO");
        btnRemoverLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dataRetiradaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 114, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataDevoluLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(tipoClienteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnAlocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoLocacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(btnRemoverLocacao)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataRetiradaLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDevoluLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoClienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlocarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocarVeiculoActionPerformed
        if(validarCampos()){
           //incompleto
            JOptionPane.showMessageDialog(null, "Operação efetuada com sucesso");
            limparCampos();
            
        }
        
        
    }//GEN-LAST:event_btnAlocarVeiculoActionPerformed

    private void tipoLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoLocacaoActionPerformed

    private void tipoClienteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoClienteBoxActionPerformed
        if(tipoClienteBox.getSelectedIndex()==1){
            campoDado.setText("  .   .   /    -  ");
            tipocliente = 2;
        }else{
            campoDado.setText("   .   .   -  ");
            tipocliente = 1;

        }
    }//GEN-LAST:event_tipoClienteBoxActionPerformed

    private void campoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDadoActionPerformed

    private void dataRetiradaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRetiradaLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataRetiradaLocacaoActionPerformed

    private void dataDevoluLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDevoluLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDevoluLocacaoActionPerformed

    private void btnRemoverLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverLocacaoActionPerformed
        // TODO add your handling code here:
        if(validarCampos()){
            Cliente pf = new Cliente();
            Servico service = new Servico();
            Locacao locacao = new Locacao();
            
            String cnhEmString = cnhMotorista.getText();
            int cnhMotorista = Integer.parseInt(cnhEmString);
            locacao.setCnhMotorista(cnhMotorista);
            locacao.setPlacaVeiculo(placaVeiculoLoc.getText());
            pf = service.buscarPessoaFisica(campoDado.getText());
            if(pf != null){
              locacao.setIdCliente(pf.getPFisica().getId());   
            } locacao.setIdCliente(pf.getPFisica().getId()); 
            //locacao.setIdLocacao();
            locacao.setDataRetirada(service.formatarDataEntrada(dataRetiradaLocacao.getText()));
            locacao.setDataDevolucao(service.formatarDataEntrada(dataDevoluLocacao.getText()));
            LocacaoService lService = new LocacaoService();
            lService.doLocacao(locacao);
            JOptionPane.showMessageDialog(null, "Operação efetuada com sucesso");
            limparCampos();
        }
            
    }//GEN-LAST:event_btnRemoverLocacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocacaoJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocarVeiculo;
    private javax.swing.JButton btnRemoverLocacao;
    private javax.swing.JTextField campoDado;
    private javax.swing.JTextPane cnhMotorista;
    private javax.swing.JFormattedTextField dataDevoluLocacao;
    private javax.swing.JFormattedTextField dataRetiradaLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane placaVeiculoLoc;
    private javax.swing.JComboBox<String> tipoClienteBox;
    private javax.swing.JComboBox<String> tipoLocacao;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        String dataRetirada = formatarData(dataRetiradaLocacao.getText());
        String dataDevolucao = formatarData(dataDevoluLocacao.getText());
        String cnhMotoristaEmString = (cnhMotorista.getText());
        String placaVeiculo = (placaVeiculoLoc.getText());
        String campoIdClienteCPFouCNPJ = (campoDado.getText());
        
        LocacaoService lService = new LocacaoService();
        Servico servico = new Servico();
        
        if(!lService.isValidoDatas(dataRetirada, dataDevolucao)){
            JOptionPane.showMessageDialog(null, "Datas inválidas");
            return false;
        }if(!lService.isValidoCNH(cnhMotoristaEmString)){
            JOptionPane.showMessageDialog(null, "CNH inválida ou não cadastrada");
            return false;
        }if(!lService.isValidoPlaca(placaVeiculo)){
            JOptionPane.showMessageDialog(null, "Placa inválida, não cadastrada ou não pertecente ao Brasil");
            return false;
            //COLOQUEI COMO PESSOA FISICA
        }if(!lService.isValidoIdClienteCPFouCNPJ(campoIdClienteCPFouCNPJ,"1")){
            JOptionPane.showMessageDialog(null, "CPF ou CNPJ inválido ou não cadastrado");
            return false;
        }
        return true;
    }
    private void limparCampos() {
        dataDevoluLocacao.setText("");
        dataRetiradaLocacao.setText("");
        campoDado.setText("");
        cnhMotorista.setText("");
        placaVeiculoLoc.setText("");
        
    }

}
